apiVersion: v2
name: cloudnative-mysql
description: A Helm chart for the CloudNative MySQL operator
type: application

version: 0.2.0
appVersion: "0.2.0"

keywords:
  - kubernetes
  - operator
  - mysql
  - database

annotations:
  kubebuilder.io/generated-by: kubebuilder
