apiVersion: v2
name: cnmsql
description: A Helm chart for the CNMSQL - CloudNative for MySQL operator
type: application

version: 0.7.1
appVersion: "0.7.1"

keywords:
- kubernetes
- operator
- mysql
- database

annotations:
  kubebuilder.io/generated-by: kubebuilder
